# Generated by Django 3.1.6 on 2021-09-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_auto_20210929_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='eng_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='kz_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='ru_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
